import { base } from '$app/paths';
import type { ItemQty } from '../types';

/** item name -> its 1-level ingredient list (from recipes.json, generated by
 * api/fetch-questlines.mjs). Absent key means "no known recipe" — either the
 * item isn't craftable, or it never appeared as a quest-required item's
 * ingredient in the source data. */
let recipesByItem = $state<Map<string, ItemQty[]>>(new Map());
let recipesHydrated = $state(false);
let recipesError = $state(false);
let loadPromise: Promise<void> | null = null;

function isItemQtyArray(v: unknown): v is ItemQty[] {
	return (
		Array.isArray(v) &&
		v.every(
			(e) =>
				e && typeof e === 'object' && typeof e.item === 'string' && typeof e.qty === 'number'
		)
	);
}

function isRecipesRecord(v: unknown): v is Record<string, ItemQty[]> {
	return (
		!!v && typeof v === 'object' && !Array.isArray(v) && Object.values(v).every(isItemQtyArray)
	);
}

async function fetchRecipes(): Promise<void> {
	try {
		const res = await fetch(`${base}/recipes.json`);
		if (!res.ok) throw new Error(`recipes.json fetch failed: ${res.status}`);
		const parsed: unknown = await res.json();
		if (!isRecipesRecord(parsed)) throw new Error('recipes.json failed shape validation');
		recipesByItem = new Map(Object.entries(parsed));
	} catch (err) {
		console.error(err);
		recipesError = true;
	} finally {
		recipesHydrated = true;
	}
}

/** Idempotent: safe to call from every mount, only fetches on the first call. */
export function loadRecipes(): Promise<void> {
	if (!loadPromise) {
		loadPromise = fetchRecipes();
	}
	return loadPromise;
}

/** Clears the cached fetch and re-runs it — for a "retry" action after a failed fetch,
 * so the user isn't forced into a full page reload to recover from a transient network
 * blip. */
export function retryRecipes(): Promise<void> {
	recipesError = false;
	loadPromise = null;
	return loadRecipes();
}

export function getRecipesState() {
	return {
		get recipesByItem() {
			return recipesByItem;
		},
		get recipesHydrated() {
			return recipesHydrated;
		},
		get recipesError() {
			return recipesError;
		}
	};
}